[project]
name = "proyecto-dir-esp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyserial>=3.5",
    "Flask >= 3.1",
    "Flask-socketio >= 5",
]
